name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

env:
  RUST_MIN_STACK: "67108864"
  RUST_TOOLCHAIN: "1.96.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@1.96.0
        with:
          targets: thumbv7em-none-eabihf

      - uses: cargo-bins/cargo-binstall@main

      - name: Install build tools
        run: |
          cargo binstall cargo-make flip-link cargo-binutils -y

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2
        with:
          key: nrf52840

      - name: Build firmware
        run: |
          cargo build --release --bin central
          cargo build --release --bin peripheral_left
          cargo build --release --bin peripheral_right

      - name: Create hex files (central)
        run: |
          cargo objcopy --release --bin central -- -O ihex asterisk-flake-central.hex

      - name: Create hex files (peripheral_left)
        run: |
          cargo objcopy --release --bin peripheral_left -- -O ihex asterisk-flake-peripheral_left.hex

      - name: Create hex files (peripheral_right)
        run: |
          cargo objcopy --release --bin peripheral_right -- -O ihex asterisk-flake-peripheral_right.hex

      - name: Install uf2 converter
        run: cargo binstall cargo-hex-to-uf2 -y

      - name: Create uf2 files (central)
        run: |
          cargo hex-to-uf2 --input-path asterisk-flake-central.hex --output-path asterisk-flake-central.uf2 --family nrf52840

      - name: Create uf2 files (peripheral_left)
        run: |
          cargo hex-to-uf2 --input-path asterisk-flake-peripheral_left.hex --output-path asterisk-flake-peripheral_left.uf2 --family nrf52840

      - name: Create uf2 files (peripheral_right)
        run: |
          cargo hex-to-uf2 --input-path asterisk-flake-peripheral_right.hex --output-path asterisk-flake-peripheral_right.uf2 --family nrf52840

      - name: Upload uf2 artifacts
        uses: actions/upload-artifact@v7
        with:
          name: asterisk-flake-firmware_uf2
          path: "*.uf2"

      - name: Upload hex artifacts
        uses: actions/upload-artifact@v7
        with:
          name: asterisk-flake-firmware_hex
          path: "*.hex"

      - name: Upload elf artifacts
        uses: actions/upload-artifact@v7
        with:
          name: asterisk-flake-firmware_elf
          path: |
            target/thumbv7em-none-eabihf/release/central
            target/thumbv7em-none-eabihf/release/peripheral_left
            target/thumbv7em-none-eabihf/release/peripheral_right
